/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_peercast_core_PeerCastService */

#ifndef _Included_org_peercast_core_PeerCastService
#define _Included_org_peercast_core_PeerCastService
#ifdef __cplusplus
extern "C" {
#endif
#undef org_peercast_core_PeerCastService_BIND_ABOVE_CLIENT
#define org_peercast_core_PeerCastService_BIND_ABOVE_CLIENT 8L
#undef org_peercast_core_PeerCastService_BIND_ADJUST_WITH_ACTIVITY
#define org_peercast_core_PeerCastService_BIND_ADJUST_WITH_ACTIVITY 128L
#undef org_peercast_core_PeerCastService_BIND_ALLOW_OOM_MANAGEMENT
#define org_peercast_core_PeerCastService_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef org_peercast_core_PeerCastService_BIND_AUTO_CREATE
#define org_peercast_core_PeerCastService_BIND_AUTO_CREATE 1L
#undef org_peercast_core_PeerCastService_BIND_DEBUG_UNBIND
#define org_peercast_core_PeerCastService_BIND_DEBUG_UNBIND 2L
#undef org_peercast_core_PeerCastService_BIND_IMPORTANT
#define org_peercast_core_PeerCastService_BIND_IMPORTANT 64L
#undef org_peercast_core_PeerCastService_BIND_NOT_FOREGROUND
#define org_peercast_core_PeerCastService_BIND_NOT_FOREGROUND 4L
#undef org_peercast_core_PeerCastService_BIND_WAIVE_PRIORITY
#define org_peercast_core_PeerCastService_BIND_WAIVE_PRIORITY 32L
#undef org_peercast_core_PeerCastService_CONTEXT_IGNORE_SECURITY
#define org_peercast_core_PeerCastService_CONTEXT_IGNORE_SECURITY 2L
#undef org_peercast_core_PeerCastService_CONTEXT_INCLUDE_CODE
#define org_peercast_core_PeerCastService_CONTEXT_INCLUDE_CODE 1L
#undef org_peercast_core_PeerCastService_CONTEXT_RESTRICTED
#define org_peercast_core_PeerCastService_CONTEXT_RESTRICTED 4L
#undef org_peercast_core_PeerCastService_MODE_APPEND
#define org_peercast_core_PeerCastService_MODE_APPEND 32768L
#undef org_peercast_core_PeerCastService_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define org_peercast_core_PeerCastService_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef org_peercast_core_PeerCastService_MODE_MULTI_PROCESS
#define org_peercast_core_PeerCastService_MODE_MULTI_PROCESS 4L
#undef org_peercast_core_PeerCastService_MODE_PRIVATE
#define org_peercast_core_PeerCastService_MODE_PRIVATE 0L
#undef org_peercast_core_PeerCastService_MODE_WORLD_READABLE
#define org_peercast_core_PeerCastService_MODE_WORLD_READABLE 1L
#undef org_peercast_core_PeerCastService_MODE_WORLD_WRITEABLE
#define org_peercast_core_PeerCastService_MODE_WORLD_WRITEABLE 2L
#undef org_peercast_core_PeerCastService_START_CONTINUATION_MASK
#define org_peercast_core_PeerCastService_START_CONTINUATION_MASK 15L
#undef org_peercast_core_PeerCastService_START_FLAG_REDELIVERY
#define org_peercast_core_PeerCastService_START_FLAG_REDELIVERY 1L
#undef org_peercast_core_PeerCastService_START_FLAG_RETRY
#define org_peercast_core_PeerCastService_START_FLAG_RETRY 2L
#undef org_peercast_core_PeerCastService_START_NOT_STICKY
#define org_peercast_core_PeerCastService_START_NOT_STICKY 2L
#undef org_peercast_core_PeerCastService_START_REDELIVER_INTENT
#define org_peercast_core_PeerCastService_START_REDELIVER_INTENT 3L
#undef org_peercast_core_PeerCastService_START_STICKY
#define org_peercast_core_PeerCastService_START_STICKY 1L
#undef org_peercast_core_PeerCastService_START_STICKY_COMPATIBILITY
#define org_peercast_core_PeerCastService_START_STICKY_COMPATIBILITY 0L
#undef org_peercast_core_PeerCastService_MSG_GET_APPLICATION_PROPERTIES
#define org_peercast_core_PeerCastService_MSG_GET_APPLICATION_PROPERTIES 0L
#undef org_peercast_core_PeerCastService_MSG_GET_CHANNELS
#define org_peercast_core_PeerCastService_MSG_GET_CHANNELS 1L
#undef org_peercast_core_PeerCastService_MSG_GET_STATS
#define org_peercast_core_PeerCastService_MSG_GET_STATS 2L
#undef org_peercast_core_PeerCastService_MSG_CMD_CHANNEL_BUMP
#define org_peercast_core_PeerCastService_MSG_CMD_CHANNEL_BUMP 16L
#undef org_peercast_core_PeerCastService_MSG_CMD_CHANNEL_DISCONNECT
#define org_peercast_core_PeerCastService_MSG_CMD_CHANNEL_DISCONNECT 17L
#undef org_peercast_core_PeerCastService_MSG_CMD_CHANNEL_KEEP_YES
#define org_peercast_core_PeerCastService_MSG_CMD_CHANNEL_KEEP_YES 18L
#undef org_peercast_core_PeerCastService_MSG_CMD_CHANNEL_KEEP_NO
#define org_peercast_core_PeerCastService_MSG_CMD_CHANNEL_KEEP_NO 19L
#undef org_peercast_core_PeerCastService_MSG_CMD_SERVENT_DISCONNECT
#define org_peercast_core_PeerCastService_MSG_CMD_SERVENT_DISCONNECT 32L
#undef org_peercast_core_PeerCastService_NOTIFY_CHANNEL_START
#define org_peercast_core_PeerCastService_NOTIFY_CHANNEL_START 0L
#undef org_peercast_core_PeerCastService_NOTIFY_CHANNEL_UPDATE
#define org_peercast_core_PeerCastService_NOTIFY_CHANNEL_UPDATE 1L
#undef org_peercast_core_PeerCastService_NOTIFY_CHANNEL_STOP
#define org_peercast_core_PeerCastService_NOTIFY_CHANNEL_STOP 2L
/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeStart
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_peercast_core_PeerCastService_nativeStart
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_peercast_core_PeerCastService_nativeQuit
  (JNIEnv *, jobject);

/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeGetChannels
 * Signature: ()Landroid/os/Bundle;
 */
JNIEXPORT jobject JNICALL Java_org_peercast_core_PeerCastService_nativeGetChannels
  (JNIEnv *, jobject);

/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeGetStats
 * Signature: ()Landroid/os/Bundle;
 */
JNIEXPORT jobject JNICALL Java_org_peercast_core_PeerCastService_nativeGetStats
  (JNIEnv *, jobject);

/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeGetApplicationProperties
 * Signature: ()Landroid/os/Bundle;
 */
JNIEXPORT jobject JNICALL Java_org_peercast_core_PeerCastService_nativeGetApplicationProperties
  (JNIEnv *, jobject);

/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeChannelCommand
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_peercast_core_PeerCastService_nativeChannelCommand
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeDisconnectServent
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_peercast_core_PeerCastService_nativeDisconnectServent
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_peercast_core_PeerCastService
 * Method:    nativeClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_peercast_core_PeerCastService_nativeClassInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
